# Generated by Django 4.0.6 on 2022-08-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.slideshow')),
            ],
        ),
        migrations.DeleteModel(
            name='SlideshowSlide',
        ),
    ]
