# Generated by Django 4.0.6 on 2022-08-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_slide_slideshowslide'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlideshowSlide',
            new_name='Slide',
        ),
    ]
