# Generated by Django 4.0.6 on 2022-08-10 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_slideshowslide_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='timer',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
