# Generated by Django 4.0.6 on 2022-08-10 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_slideshow_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='focal_point',
            field=models.CharField(choices=[('top-left', 'Top-left'), ('top', 'Top'), ('top-right', 'Top-Right'), ('center-left', 'Center'), ('center', 'Center'), ('center-right', 'Center-Right'), ('bottom-left', 'Bottom-Left'), ('bottom', 'Bottom'), ('bottom-right', 'Bottom-Right')], default='center', max_length=20),
        ),
    ]
