# Generated by Django 4.0.6 on 2022-08-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_slide_focal_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='focal_point',
            field=models.CharField(choices=[('top-left', 'Top-left'), ('top', 'Top'), ('top-right', 'Top-right'), ('center-left', 'Center-left'), ('center', 'Center'), ('center-right', 'Center-right'), ('bottom-left', 'Bottom-left'), ('bottom', 'Bottom'), ('bottom-right', 'Bottom-right')], default='center', max_length=20),
        ),
    ]
