# Generated by Django 4.0.6 on 2022-08-12 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('rating', models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('albums', models.ManyToManyField(related_name='pictures', to='main.album')),
                ('suggested_albums', models.ManyToManyField(related_name='potential_pictures', to='main.album')),
            ],
        ),
    ]
