# Generated by Django 4.0.6 on 2022-08-13 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_picture_user_alter_picture_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slideshow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='main.slideshow'),
        ),
    ]
