# Generated by Django 4.0.6 on 2022-08-21 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_album_name_alter_picture_albums_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='date_uploaded',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
