# Generated by Django 4.0.6 on 2022-08-24 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_picture_albums_alter_picture_suggested_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
