# Generated by Django 4.0.6 on 2022-09-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_album_author_alter_picture_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='share_status',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10),
        ),
    ]
