# Generated by Django 4.0.6 on 2022-09-08 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_album_share_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='shared_with',
            field=models.ManyToManyField(blank=True, null=True, related_name='albums_shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
