# Generated by Django 4.0.6 on 2022-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_application_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='application_accepted',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
