# Generated by Django 4.0.6 on 2022-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_application_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics/'),
        ),
    ]
