# Generated by Django 4.0.6 on 2022-09-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_friendship_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unique_link_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
